### ISSUE TITLE
More condensed output

### ISSUE THREAD

**Issue by billgraziano** [nao1215/hottest#3]
## What problem does this feature solve?
I'm working on an application that I test against multiple versions of a database server.  So the tests run 5-10 times each time I test.  After looking at the output a few times, a more condensed version of the output would be interesting to me.

## Describe the solution you'd like
1. Eliminate the line that says "hottest v0.0.1 execute 'go test'"
2. Eliminate the blank line after it.
3. I LOVE the dots.....!
4. Compress the results down to a single line.  Or maybe only do this if all tests pass?  Maybe something like this?

```
Results: 265/0/0 (30s)
```

That is total tests, failed, and skipped.  I really mostly care about the failed number, but the others are kind of nice to see.  Printing the duration in a more compact format would be nice.

## Describe alternatives you've considered
Maybe a flag for verbose vs condensed output?  Or a JSON config file?  I run these inside batch files so putting the same flag in each time isn't a problem.  But then the parameters don't match go test.  I don't know :-) 

## Additional context
* I really, really like the dots as progress.  I've been using that in some CLI stuff I've written recently.
* I like the terseness of the test failure message.  It is very easy to see.  My app can write lots of debugging stuff and I'm glad you discarded that.
* I realize you just released this (5 hours ago?!?!) but it's already helpful to me!

**Comment by nao1215** [comment]
@billgraziano 
Thank you for using the `hottest` command.
  
I have implemented your request (please see #4 ). I have released it as v0.0.2, so please execute the following command:
```shell
go install github.com/nao1215/hottest@v0.0.2
```

By the way, I'm also creating a command to update the binary installed with go install (it's called [nao1215/gup](https://github.com/nao1215/gup)). 
Feel free to use it if you're interested.
